#!/usr/bin/env bash

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"

_log() {
  if declare -f "$1" >/dev/null 2>&1; then
    "$1" "${@:2}"
  else
    echo "${*:2}"
  fi
}

load_env() {
  if [[ -f "${ENV_FILE}" ]]; then
    set -o allexport
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
    set +o allexport
    _log log_info "Loaded environment from ${ENV_FILE}"
  else
    _log log_warn "No .env file found at ${ENV_FILE}"
  fi
}

create_env_interactive() {
  if [[ -f "${ENV_FILE}" ]]; then
    read -r -p ".env already exists at ${ENV_FILE}. Overwrite? [y/N]: " answer
    case "${answer}" in
      y|Y) ;;
      *) _log log_info "Keeping existing .env"; return 0 ;;
    esac
  fi

  echo "Configure environment for RateCore"

  read -rsp "BOT_TOKEN (Telegram bot token): " bot_token
  echo
  read -r -p "TELEGRAM_ADMIN_ID (admin user id): " admin_id
  read -r -p "RCORE_API_BASE_URL [http://localhost:8080]: " api_base
  api_base=${api_base:-http://localhost:8080}
  read -r -p "RCORE_HTTP_PORT [8080]: " http_port
  http_port=${http_port:-8080}
  read -r -p "RCORE_LOG_LEVEL [info]: " log_level
  log_level=${log_level:-info}

  read -r -p "RCORE_BINANCE_BASE_URL (optional): " binance_base
  read -r -p "RCORE_FOREX_BASE_URL (optional): " forex_base
  read -r -p "RCORE_IRR_BASE_URL (optional): " irr_base
  read -rsp "RCORE_IRR_API_KEY (optional): " irr_api_key
  echo
  read -r -p "RCORE_METALS_BASE_URL (optional): " metals_base

  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/helpers/env.sh
BOT_TOKEN=${bot_token}
TELEGRAM_ADMIN_ID=${admin_id}
RCORE_API_BASE_URL=${api_base}

RCORE_HTTP_PORT=${http_port}
RCORE_LOG_LEVEL=${log_level}

RCORE_BINANCE_BASE_URL=${binance_base}
RCORE_FOREX_BASE_URL=${forex_base}
RCORE_IRR_BASE_URL=${irr_base}
RCORE_IRR_API_KEY=${irr_api_key}
RCORE_METALS_BASE_URL=${metals_base}
EOF

  _log log_success "Environment written to ${ENV_FILE}"
}
